
---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

TODO:
- Check issue with nga yang in lucky dream

#Data import

```{r message=FALSE}
library(tidyverse)
library(tidyr)
library(rlang)
library(rezonateR)
library(purrr)
library(here)

setwd("~/GitHub/lhasa-reference-tracking/shanti/")
discoNames = c("three-caught-8261", "three-parting-2569",
               "three-friction-2883", "three-luckydreamalt-8296",
               "three-scold-21496", "virginia-altar-2563",
               "virginia-library-20766", "virginia-neighbour-2565",
               "three-chupa-8346", "three-counsel-8176",
               "lhasa-interview-2561",
               "three-butter-8511", "three-dadronpudron-8256",
               "three-vegetables-9201", "three-wrap-8561",
               "three-dadronmum-2537", "lhasa-reminisce-11421",
               "three-baby-8121", "island-rollerstaff-9331",
               "three-upset-2535", "island-sangdadorje-8501",
               "dramatroupe-script-8421", "virginia-america-2564"
)

df = lapply(discoNames, function(x) rez_load(paste0('wo1_3_rezrDF/', x, ".Rdata"))) %>% reduce(rez_bind_rows)
saveRDS(df, "wo3/20241111_wodata.rds")
```

Quick check:
```{r}
clauses = df %>% group_by(verbID) %>% count
nrow(clauses)
clauses %>% filter(n == 1)
```



# Features

```{r}
featsChosen = c("argTypeNew",
           "noPrevMentions", "noPrevZero", "noNextMentions", "noNextZero",
           "haveBridges", "identifiable", "local", "justFirst", "justLast", 
            "interrog", "animate",
           "self", "addressee", "length", "pronom", "noPrevMentionsFar", "noNextMentionsFar")
featsQuant = c("noPrevMentions", "noPrevZero", "noNextMentions", "noNextZero",
               "justFirst", "justLast", "length", "noPrevMentionsFar", "noNextMentionsFar")

log_p1 = function(x) log(x + 1)
df = df %>% mutate(haveBridges = as.integer(haveBridges),
                     justFirst = as.integer(justFirst),
                     justLast = as.integer(justLast),
                     local = as.integer(local),
                     identifiable = as.integer(identifiable == "i"),
                     topic = as.integer(topic),
                     interrog = as.integer(interrog),
                     animate = as.integer(animate),
                     self = as.integer(self),
                     addressee = as.integer(addressee),
                     argType = as.factor(argType),
                     pronom = as.integer(pronom)) %>%
  mutate(argTypeNew = as.factor(case_when(argType == "T" ~ "P",
                                       argType == "A" ~ "Base",
                                       argType == "S" ~ "Base",
                                       argType == "COPS" ~ "Base",
                                       argType == "COPLOC" ~ "Base",
                             T ~ argType))) %>%
  mutate(across(all_of(featsQuant), log_p1)) 
```

```{r}
cols_na_present = df %>% sapply(function(x) any(is.na(x)))
intersect(featsChosen, names(cols_na_present)[which(cols_na_present)])
```

```{r}
library(FactoMineR)
x_famd = df %>%
    select(all_of(featsChosen)) %>%
  FAMD(ncp = 14)
```
